### ISSUE TITLE
NuGet not up-to-date?

### ISSUE THREAD

**Issue by YaakovN** [fsprojects/FSharp.Compatibility#4]
According to [NuGet](https://www.nuget.org/packages/FSharp.Compatibility.OCaml) the OCaml lib was last published on there on 2013-07-07 (v0.1.10)
But according to https://github.com/fsprojects/FSharp.Compatibility/commit/57861ff28d6d69dee3c6e221973926854a48fcf4, the latest changes were only applied on 2013-07-20.

The specific issue I experience after switching from the old Ocaml Combatibility library in Powerpack to yours, is that "invalid_arg" (Pervasives.fs) "is not defined".
Would you mind updating the package on Nuget?

**Comment by wallymathieu** [comment]
Is this still valid @jmquigs ?

**Comment by jmquigs** [comment]
Probably.  I don't think I have nugent access but I will try to update them.

**Comment by wallymathieu** [comment]
Perhaps @forki can help with that (access to nuget)?

**Comment by forki** [comment]
I don't think I have access to that particular nuget package

**Comment by wallymathieu** [comment]
Looks like the user 'fsprojects' does have access to all of them. https://www.nuget.org/packages?q=FSharp.Compatibility @jack-pappas looks like he has access to some of them (but not all)

**Comment by YaakovN** [comment]
If you guys are already looking at this, would this be a good moment to add
a "net standard" option?
Thanks.

**Comment by wallymathieu** [comment]
Netstandard conversion is a separate issue. Someone needs to go through the projects and change fsproj to the new format and see what breaks (and check if it's possible to target lower netstandard versions than 2.0).

**Comment by wallymathieu** [comment]
So who to talk to then @forki ?

**Comment by forki** [comment]
To the original authors. They should try to find new maintainers.

Am 04.02.2018 14:22 schrieb "Oskar Gewalli" <notifications@github.com>:

**Comment by wallymathieu** [comment]
Looks like @jack-pappas is the original author.

**Comment by dsyme** [comment]
@wallymathieu We can make you an owner on the relevant packages.  Is that correct?

**Comment by wallymathieu** [comment]
@dsyme if you want help with publishing the nuget packages, then yes.

If there is some other maintainer of this project that is willing to publish it to nuget, for instance it looks like there are maintainers with commit access to this repo that does not have nuget publish access (I do not have commit access to this repo).

**Comment by jmquigs** [comment]
@wallymathieu is it advisable to build one set of packages now, and then after upgrading the project to F# 4.0+, bump the version number and upload another set?  Sorry if its a basic question, I'm a nuget nuub. 😄

**Comment by wallymathieu** [comment]
@jmquigs depends on what you win by doing that. It looks like it was [a while](https://www.nuget.org/packages?q=fsharp.compatibility) since the nuget packages got pushed. Is there any need for code changes by changing f# compiler and FSharp.Core library?

**Comment by jmquigs** [comment]
@wallymathieu some of the code will need to change I'm sure.  If the project is upgraded to the newer version, then @gusty can also upgrade the F#+ dependency to a more recent version, but its probably not a big priority.

**Comment by wallymathieu** [comment]
It looks like the Haskell and OCaml compatibility projects are separate, so any change of f# and `FSharp.Core` can be applied to the separate subprojects.

**Comment by jack-pappas** [comment]
Sorry for the late reply, I was away on holiday and I'm just now catching up on emails.

Some background: I started this repo 5-6 years ago when porting some OCaml-based code to F#. I wanted to avoid changing the code more than necessary, so I created the _FSharp.Compatibility.OCaml_ library to provide select functions from the OCaml standard library (ported so they'd work for F# / .NET). Later, I merged in some code from the old F# PowerPack which aimed to do the same thing (provide an OCaml compatibility layer). The other _FSharp.Compatibility.OCaml.*_ subprojects are separate primarily for licensing reasons -- they contain code taken directly from the OCaml standard library so are LGPL-licensed rather than Apache 2.0 as the other projects are.

Some time later, I had some bits of Haskell and SML code I wanted to try porting to F# in the same way so I created similar projects for those languages. I started a new job not long after and put these on the back burner and they've been there ever since.

Do we actually need to add any NuGet permissions here? Or just publish new versions of the package(s)?

**Comment by wallymathieu** [comment]
It looks like the only relevant change to release is the `FSharp.Compatibility.Haskell` as far as I can see?

**Comment by wallymathieu** [comment]
So once that has been released, perhaps this issue can be closed?

**Comment by jmquigs** [comment]
@jack-pappas thanks for commenting.  I think we just need to publish new versions of the packages.  Other than the recent Haskell changes, I made some minor changes to the OCaml packages some time ago, mostly to fix the build, that I don't think were ever released on NuGet.  So it would be nice to have new packages for Haskell and OCaml at least.

**Comment by dsyme** [comment]
I'm happy to have all three of you @jmquigs, @wallymathieu and  @jack-pappas as co-owners.  I'll update the permissions (if I can find your nuget IDs)

**Comment by dsyme** [comment]
Actually i can't find either of you @wallymathieu	and @jmquigs :)  Please list your nuget.org IDs below and we can add you as package owners

**Comment by wallymathieu** [comment]
I have a bit of an odd names as usual : https://www.nuget.org/profiles/ozzymcduff is the nuget user I use.

**Comment by jmquigs** [comment]
@dsyme Thanks!  I just created my account: https://www.nuget.org/profiles/jmquigs

**Comment by wallymathieu** [comment]
@jmquigs let's plan what to do here then. Do you need any help or anything?

**Comment by jmquigs** [comment]
@wallymathieu actually I could use some help, since I haven't updated the packages before.  Should I just use the travis artifacts, or is there a project here that has a reference nuget setup that I could look at?

**Comment by wallymathieu** [comment]
I would guess that it would be nice to just upload the artifacts to nuget. Otherwise you would need to locally do the same thing as is done on the build server. However, I can't seem to find [any Appveyor artifacts](https://ci.appveyor.com/project/fsprojectsgit/fsharp-compatibility/build/artifacts) or [Travis artifacts](https://travis-ci.org/fsprojects/FSharp.Compatibility/builds/335933024)?

**Comment by jmquigs** [comment]
It looks like the appveyor config wasn't set up to find the artifacts.  I fixed that in my fork and now it is finding them: https://ci.appveyor.com/project/jmquigs/fsharp-compatibility/build/artifacts 
Now I just need to make the build generate the nuget files.  The spec files are in the repo, so that shouldn't be hard.  Then its just a version bump and a rebuild, followed by a push of the files to the NuGet Repro.

**Comment by wallymathieu** [comment]
They should be uploaded now.

**Comment by wallymathieu** [comment]
They are validating right now.
